// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file smart_home.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "smart_home.h"

#include <ucdr/microcdr.h>
#include <string.h>

bool smart_home_LedCommand_serialize_topic(ucdrBuffer* writer, const smart_home_LedCommand* topic)
{
    bool success = true;

        success &= ucdr_serialize_uint16_t(writer, topic->id);

        success &= ucdr_serialize_uint16_t(writer, topic->brightness);

    return success && !writer->error;
}

bool smart_home_LedCommand_deserialize_topic(ucdrBuffer* reader, smart_home_LedCommand* topic)
{
    bool success = true;

        success &= ucdr_deserialize_uint16_t(reader, &topic->id);

        success &= ucdr_deserialize_uint16_t(reader, &topic->brightness);

    return success && !reader->error;
}

uint32_t smart_home_LedCommand_size_of_topic(const smart_home_LedCommand* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 2) + 2;

        size += ucdr_alignment(size, 2) + 2;

    return size - previousSize;
}

bool smart_home_ServoCommand_serialize_topic(ucdrBuffer* writer, const smart_home_ServoCommand* topic)
{
    bool success = true;

        success &= ucdr_serialize_uint16_t(writer, topic->angle);
    return success && !writer->error;
}

bool smart_home_ServoCommand_deserialize_topic(ucdrBuffer* reader, smart_home_ServoCommand* topic)
{
    bool success = true;

        success &= ucdr_deserialize_uint16_t(reader, &topic->angle);
    return success && !reader->error;
}

uint32_t smart_home_ServoCommand_size_of_topic(const smart_home_ServoCommand* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 2) + 2;

    return size - previousSize;
}

bool smart_home_DeviceState_serialize_topic(ucdrBuffer* writer, const smart_home_DeviceState* topic)
{
    bool success = true;

        success &= ucdr_serialize_uint16_t(writer, topic->led1);

        success &= ucdr_serialize_uint16_t(writer, topic->led2);

        success &= ucdr_serialize_uint16_t(writer, topic->servo_angle);

    return success && !writer->error;
}

bool smart_home_DeviceState_deserialize_topic(ucdrBuffer* reader, smart_home_DeviceState* topic)
{
    bool success = true;

        success &= ucdr_deserialize_uint16_t(reader, &topic->led1);

        success &= ucdr_deserialize_uint16_t(reader, &topic->led2);

        success &= ucdr_deserialize_uint16_t(reader, &topic->servo_angle);

    return success && !reader->error;
}

uint32_t smart_home_DeviceState_size_of_topic(const smart_home_DeviceState* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 2) + 2;

        size += ucdr_alignment(size, 2) + 2;

        size += ucdr_alignment(size, 2) + 2;

    return size - previousSize;
}
