// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file smart_home.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _smart_home_H_
#define _smart_home_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdint.h>
#include <stdbool.h>

typedef struct smart_home_LedCommand
{
    uint16_t id;
    uint16_t brightness;
} smart_home_LedCommand;

struct ucdrBuffer;

bool smart_home_LedCommand_serialize_topic(struct ucdrBuffer* writer, const smart_home_LedCommand* topic);
bool smart_home_LedCommand_deserialize_topic(struct ucdrBuffer* reader, smart_home_LedCommand* topic);
uint32_t smart_home_LedCommand_size_of_topic(const smart_home_LedCommand* topic, uint32_t size);

typedef struct smart_home_ServoCommand
{
    uint16_t angle;
} smart_home_ServoCommand;

struct ucdrBuffer;

bool smart_home_ServoCommand_serialize_topic(struct ucdrBuffer* writer, const smart_home_ServoCommand* topic);
bool smart_home_ServoCommand_deserialize_topic(struct ucdrBuffer* reader, smart_home_ServoCommand* topic);
uint32_t smart_home_ServoCommand_size_of_topic(const smart_home_ServoCommand* topic, uint32_t size);

typedef struct smart_home_DeviceState
{
    uint16_t led1;
    uint16_t led2;
    uint16_t servo_angle;
} smart_home_DeviceState;

struct ucdrBuffer;

bool smart_home_DeviceState_serialize_topic(struct ucdrBuffer* writer, const smart_home_DeviceState* topic);
bool smart_home_DeviceState_deserialize_topic(struct ucdrBuffer* reader, smart_home_DeviceState* topic);
uint32_t smart_home_DeviceState_size_of_topic(const smart_home_DeviceState* topic, uint32_t size);


#ifdef __cplusplus
}
#endif

#endif // _smart_home_H_